application: lanie-iannucci
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  upload: static/index.html
  static_files: static/index.html

- url: (.*)
  upload: static/\1
  static_files: static/\1

libraries:
- name: webapp2
  version: "2.5.2"
